services:
  eco-postgres:
    container_name: eco-postgres
    image: 'postgres:16'
    environment:
      - 'POSTGRES_DB=eco-postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '2000:5432'
  eco-redis:
    container_name: eco-redis
    image: 'redis:7.2.4'
    ports:
      - '6000:6379'