services:
  eco-postgres:
    image: 'postgres:16'
    container_name: eco-postgres
    ports:
      - '2000:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: eco_postgres
  eco-redis:
    container_name: eco-redis
    image: 'redis:7.2.4'
    ports:
      - '6000:6379'