spring:
  mail:
    host: smtp.gmail.com
    username: webstore.perfume@gmail.com
    password: lnlzzizbarytqfnz
    port: 465
    protocol: smtps
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:2000/postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
eco:
  security:
    token:
      expiration: 86400
      secret: SzqXrBuEVJOVLqjGeenHM6aNo8j3KJiKJ4LWB3oZf8aSlkkQgw6L6ZwklCbQK2Y/
  otp:
    retry-wait-time: 5 # in seconds
    retry-count: 3
    time-to-live: 60 # in seconds:
